Default: &defaults
  database: yesod-auth-account-example.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-auth-account-example_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-auth-account-example_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-auth-account-example_production.sqlite3
  poolsize: 100
  <<: *defaults
